"""add status to analyses

Revision ID: c30ff6b69613
Revises: 2991ec87739a
Create Date: 2026-09-01 21:36:37.059996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c30ff6b69613'
down_revision: Union[str, Sequence[str], None] = '2991ec87739a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('status', sa.String(), nullable=False, server_default='pending'))
    op.alter_column('analyses', 'result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('analyses', 'status')
    # ### end Alembic commands ###
